### ISSUE TITLE
can't apply to string valued variable?

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#10]
Am I right in thinking that "use Inline Lua => " cannot be applied to a string valued variable?  I find the following function works,
````
sub readLua{
    use Inline Lua => "function luaFunction (x,y) return x * y end";
    return &luaFunction(2,3); }
```
but the next one does not.
```
sub readLua{
    my $funstr = "function luaFunction (x,y) return x * y end";
    use Inline Lua => $funstr;
    return &luaFunction(2,3); }
```

**Comment by hoelzro** [comment]
@unhandyandy This is a Perl behavior rather than an Inline::Lua one; `use` happens at compile time, and the assignment into `$funstr` happens at runtime, so when `use Inline::Lua` sees it, it is `undef`.  The following Perl script demonstrates this behavior as well:

```perl
use feature 'say';
my $message = 'hello';
BEGIN { say $message }
```

**Comment by unhandyandy** [comment]
OK, thanks.

**Comment by unhandyandy** [comment]
Is there another way to call Inline Lua?  I thought maybe 
```
use Inline Lua;
Inline::Lua( <lua string> );
```
or maybe 
```
use Inline Lua;
Inline Lua => <lua string>;
```
but those don't seem to work.

**Comment by hoelzro** [comment]
@unhandyandy You may want to check out the Inline documentation here: https://metacpan.org/pod/distribution/Inline/lib/Inline.pod

**Comment by unhandyandy** [comment]
Thanks, Inline->bind is what I need.
