### ISSUE TITLE
Lua Objects -> Perl Objects?

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#11]
Can I define an object with a method in Inline Lua and then call it in Perl?

For example, should I be able to have 
```
__Lua__
local thing = {}
thing.mt = {__index = thing}
function thing.action( x )
    return x + 1
end
```
and then call it in perl by thing->action( 3 )?

**Comment by unhandyandy** [comment]
Or maybe by 
```
@{$thing->{action}}(3)
```

**Comment by hoelzro** [comment]
@unhandyandy This is not currently possible; IIRC, `Inline::Lua` marshals objects (including tables) between the Perl and Lua environments, so tables lose their metatable.  You can, however, do the `$object->{method_name}->(@args)` trick, as long as `method_name` is a key of `$object` itself and not accessed via a metatable.

**Comment by unhandyandy** [comment]
OK, thanks.
