### ISSUE TITLE
calling lua from lua

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#12]
If I call inline lua function g from inline lua function f, does f get the pure lua version of g, the perl version, or a lua version of the perl version?

It's probably asking too much to want to use string.dump ( <function> ), but one can dream.

**Comment by hoelzro** [comment]
I'm not terribly sure, but I'm guessing it'd get the Lua version.  You can guarantee this by making g `local`.

**Comment by unhandyandy** [comment]
So if a function is declared local it won't be exported to perl?

If I have lua inlines in two different perl files, do they have access to each others' local functions?

**Comment by hoelzro** [comment]
I don't know for sure, because I'm not the original author, but I highly doubt it.  The two inlines will not be able to see each others' locals.

**Comment by unhandyandy** [comment]
Thanks.
