### ISSUE TITLE
How to inhibit variable substitution is strings?

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#14]
It seems that when a string variable is defined by
```
local str = [[ $name ]]
```
Inline::Lua performs variable substitution, even though in Lua this should be a verbatim string.  So for example if $name is undefined in the perl environment, this Inline::Lua assignment results in str = ''.

Is there a way to keep Inline::Lua from performing variable substitution like this?  I might prefer that str = '$name'.

**Comment by hoelzro** [comment]
@unhandyandy I tried the following code:

```perl
#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);

use Inline 'Lua';

my $message = 'hello';

greet();

__END__
__Lua__

function greet()
  local str = [[ $message ]]
  print(str)
end
```
and I get " $name " as the output.  Could you provide a small example that demonstrates this behavior?

**Comment by unhandyandy** [comment]
You mean you get "$message" as the output?  

Is your "use feature" line important here?  

My code is more convoluted.  I wanted to use loadstring to evaluate a string as a Lua variable.
```
local strvar = "@name"
.
.
.
local x = loadstring( strvar )()
```
Maybe the problem is with loadstring.  Is the evaluation happening in the Perl environment?

**Comment by hoelzro** [comment]
I do indeed get " $message " as the output.  I don't think the `use feature` line should affect anything, but you never know.

If you're using `loadstring` to try to get the value of a local, it will likely result in `nil`.  `localstring` can't access locals in the executing environment (at least not directly).

**Comment by unhandyandy** [comment]
Maybe the problem is that my code is split over two files?  I have one module
```
package Test;

use Inline 'Lua';
use Inline (Config => DIRECTORY => "/tmp/");

use Inline 'Lua' => <<LUA;

function testfun()
   return [[ this is a $test ]]
end

LUA

1;
```
and another file where I call testfun:
```
my $test = Test::testfun();
```
The variable $test ends up with the value 'this is a '.

**Comment by hoelzro** [comment]
Ah, ok!  You didn't mention that your Lua code was embedded in a heredoc!  Here I was testing code embedding in `__END__`. =)

So what's happening is that Perl is interpolating `$test` for you, because heredocs interpolate by default.  If you don't want a heredoc to interpolate, you have to single quotes on both sides of the heredoc terminator, like so:

```perl
use Inline Lua => <<'END_LUA';
function testfun()
  return [[ this is a $test ]]
end
END_LUA
```

**Comment by unhandyandy** [comment]
Great, thanks!
