### ISSUE TITLE
exporting variables

### ISSUE THREAD

**Issue by unhandyandy** [hoelzro/inline-lua#15]
Am I correct in thinking that while functions are automatically exported from Inline Lua to Perl, variables are not?  It seems the only way to make a variable defined in Lua available to Perl is to return it from a function.

If that's correct, what are your favorite workarounds?

If not, what am I probably doing wrong.

**Comment by hoelzro** [comment]
@unhandyandy I believe that is correct; I would just make a function that returns the variable in question.

**Comment by unhandyandy** [comment]
OK, thanks, I can deal with it.
