### ISSUE TITLE
Conversion of NV's

### ISSUE THREAD

**Issue by markov2** [hoelzro/inline-lua#32]
I had a deep dive for this.  In some cases, your detection for integers and floats fails.  Apparently, Lua does not care when you pass a string for a number, but it does when you pass a float.   I think your detection for the type of a parameter is incorrect, which is usually not detected because of forgivingness of Lua internals.

When I create a variable, which I use as a string (this may be also caused by the reuse of a SV which was printed once, at least in my Perl 5.16.1), the type becomes an SVt_PVNV (the SV has a PV and an NV).  For instance:
```perl
my $x = 43.5; print "$x";
```
To make things worse, the problem does not always show-up.  Examples:
```lua
function take_num (a)
    return a+1
end

function is_large (a)
    if a > 100.5 then return "large" else return "small" end
end
```
With the addition, in the first case, it simply works.  The comparison in the second example breaks with `error: [string "_INLINED_LUA"]:6: attempt to compare number with string`

In Inline::Lua, the switch in push_val() in Lua.xs uses SvTYPE(val) which leads the SVt_PVNV to the string version of the SV.  But I think we should prefer the NV version.  The simplest fix is to move the "case SVt_PVNV" up to its "SVt_NV" neighbour.  And the same for the IV version.

If I understand perlguts correctly, the code should reflect our preference for SV interpretations.  I suggest this replacement for the switch:
```C
    if(SvNOKp(val)) {
        lua_pushnumber(L, (lua_Number)SvNV(val));
    } else if(SvIOKp(val)) {
#if LUA_VERSION_NUM < 503
        lua_pushnumber(L, (lua_Number)SvIV(val));
#else
        lua_pushinteger(L, (lua_Integer)SvIV(val));
#endif
    } else if(SvROK(val)) {
        push_ref(L, val);
    } else {
        STRLEN n_a;
        char *cval = SvPV(val, n_a);
        lua_pushlstring(L, cval, n_a);
    }
```

**Comment by markov2** [comment]
SvROK probably before the other tests.

**Comment by hoelzro** [comment]
@markov2 Thanks for digging into this and bringing it to my attention!  I think you make a really good point, but I'm concerned about how this might affect backwards compatability with previous releases.  Do you have any ideas on how we could manage that?

**Comment by markov2** [comment]
I do not know about the internals of Lua.  Does Lua auto-convert numerics into strings?  In that case, it can not cause problems.

**Comment by hoelzro** [comment]
Sometimes it does - I guess what makes me hesitate here is that this is the first time I've seen this issue reported, and some users might be relying on the "prefers PV" behavior that the module currently provides.  I'm not happy with that preference for PVs, but at the same time I'm not keen on potentially breaking others' code, and one could always explicitly coerce a `PVNV` to an `NV` before passing it to Lua.

**Comment by markov2** [comment]
Being the maintainer of 80 CPAN modules myself, sometimes with XS, sometimes ancient (like MailTools), I am glad to see to such dedication to backwards compatibility.  In this case: you can never perfectly go from a type-less system into a typed system.

I use your module because I am working on Linkspace (formerly known as GADS), which is written by Andy (he contacted you in the past).  It is a spreadsheet like application, where people can put Lua formalas in cells to "compute something".  The parameter names of the Lua functions match column names which are typed.  When I pick-up a float from the cell to pass to Lua in a my (pad) variable, it may happen (with Perl 5.16) that the SV has been used and still has a PV (text buffer) attached to it. That depends on earlier use of that my variable.

Getting a float into an SV is never automatic: either by assignment of a float, or as result of a computation.  Having a string value as well happens all the time: when you print, f.i. to debug your code.  So, the flag SvNOKp is a really strong indication that the SV is to be interpreted as NV.

At least you should not check whether it **has** a text buffer (SVt_PVNV), but whether it is **in use** (SvPOKp)  In most cases, you will not see a difference in behaviour.  However, I the code I rewrite, there are comments like "be careful with this execution path, not to break the Lua call"... People often find a work-around.  Some are lucky until the code gets into production.

When you are really afraid to break other peoples code by repairing your algorithm, you could add a parameter to the loading of your module (like `use Inline::Lua version => 2`)  or add a function `call2` which takes the parameters in a different way.  Is that an option for you?

**Comment by hoelzro** [comment]
@markov2 Thanks for explaining your use case - it definitely makes the problem easier to think about!  For your program, you mention that the columns are typed - would it be possible to leverage the columns' types to do things like `$value . ''` or `$value + 0` to coerce the scalar values to ones `Inline::Lua` handles better, at least for the time being?

I kind of like the `use Inline::Lua version => 2` idea - if not `version` itself, then some configuration options like what [Inline::C offers](https://metacpan.org/pod/distribution/Inline-C/lib/Inline/C.pod#C-CONFIGURATION-OPTIONS).  I think I'd be ok with that!

I think you're right about `SVt_PVNV` vs `SvPOKp` - I'd happily include that change!

**Comment by hoelzro** [comment]
Huh, interesting!  What do the following one-liners output for you?  I'm on 5.32, so maybe that's making the difference:

```
$ perl -MDevel::Peek=Dump -le 'my $s = 3.1;  "$s"; print Dump($s+0.0)'
SV = NV(0x564d83a1d528) at 0x564d83a1d540
  REFCNT = 1
  FLAGS = (PADTMP,NOK,pNOK)
  NV = 3.1

$ perl -MDevel::Peek=Dump -le 'my $s = 3.1;  print Dump($s)'      
SV = NV(0x561016c492d8) at 0x561016c492f0
  REFCNT = 1
  FLAGS = (NOK,pNOK)
  NV = 3.1

```

**Comment by markov2** [comment]
On perl 5.16.1, the second has also flag PADMY.  Now this one
```bash
perl -MDevel::Peek=Dump -le 'my $s = "tic"; $s = 3.1; print Dump($s)'
SV = PVNV(0x17d55a0) at 0x17f4188
  REFCNT = 1
  FLAGS = (PADMY,NOK,pNOK)
  IV = 0
  NV = 3.1
  PV = 0x17e82b0 "tic"\0
  CUR = 3
  LEN = 16
```

**Comment by hoelzro** [comment]
@markov2 I tested this code based on your recommendations; the test suite passes, so that's a start :smile: 

```c
    if (SvNOK(val)) {
        lua_pushnumber(L, (lua_Number)SvNV(val));
    } else if (SvROK(val)) {
        push_ref(L, val);
    } else if (SvIOK(val)) {
#if LUA_VERSION_NUM < 503
        lua_pushnumber(L, (lua_Number)SvIV(val));
#else
        lua_pushinteger(L, (lua_Integer)SvIV(val));
#endif
    } else if (SvPOK(val)) {
        STRLEN n_a;
        char *cval = SvPV(val, n_a);
        lua_pushlstring(L, cval, n_a);
    } else {
        // XXX improve this
        croak("Unable to push value");
    }
```

I still feel skittish about making this the default, though - if you have a Lua function `fn` and a Perl scalar `$s`, calling `fn($s+0)` doesn't fix the problem you're running into?

**Comment by markov2** [comment]
Well, `fn($s+0)` may help, simply because it creates a new SV. But see this:
```bash
$ perl -MDevel::Peek=Dump -le 'my $s = "tic"; $s = 3.1; $s += 0.0; print Dump($s)'
SV = PVNV(0x25975a0) at 0x25b6178
  REFCNT = 1
  FLAGS = (PADMY,NOK,pNOK)
  IV = 3
  NV = 3.1
  PV = 0x25aa2a0 "tic"\0
  CUR = 3
  LEN = 16
```
Without really copying the value into a new SV, the old PV buffer stays alive.  Svt_PVNV just not the right logic to use (I hate the complexity of XS, which all its generations of macros: I never feel safe using it.)

The problem being that the software component which extracts the float is very far apart from the code which handles the Lua code.
Being extremely careful, it may be able to get it to work (as it is in the current version of the software), but when I add a debug print,
it horribly breaks.

I do not know how many users you have.  When it are only a few, I would simply make the change and go back when people start complaining.  I would also increase the major version number to signal that something important has changed..

**Comment by hoelzro** [comment]
Right - I guess what I'm wondering is if it would be possible to make sure you're coercing the scalar to an NV via `$s+0` whenever you call a Lua function `fn`, or if due to the number of places that invoke Lua functions that's just not feasible.

Regarding the number of users - I don't know how many people are really using this module, and due to its nature I imagine many of them are going to be "DarkPAN" users of sorts.  I think maybe a major version bump might be the right approach, as you suggest.

**Comment by markov2** [comment]
As I demonstrated, even when you assign a float to a scalar, it may still have a text buffer from a previous use containing an unrelated value.  In your implementation, it does not use my float, but that unrelated value.  You get reused SVs on unexpected moments.

Yes, fixing bugs may trigger issues in other people's applications.  I have experienced that often myself.  That's where regression tests are for ;-)

**Comment by hoelzro** [comment]
@markov2  Just to make sure I completely understand the issue - this is what you're running into, right?

```perl
#!/usr/bin/env perl

use strict;
use warnings;
use feature qw(say);
use experimental qw(signatures);

use Inline 'Lua';

sub innermost($v) {
    problem($v);
}

sub middle($v) {
    innermost($v);
}

sub outermost($v) {
    middle($v)
}

my $s = 1;
say "s = $s";
outermost($s);

__END__
__Lua__

function problem(v)
  return v > 5
end
```

> s = 1
> error: [string "_INLINED_LUA"]:3: attempt to compare number with string

If that's the case, I'm not talking about assigning a scalar as the solution, but rather passing an entirely new scalar to the Lua function - so `innermost` would look like that in this case:

```perl
sub innermost($v) {
    problem($v+0);
}
```

Does that solution not work for you?

**Comment by markov2** [comment]
The situation is far more complex. The issue emerge by use of 'my' to catch the value which has to be passed to Lua, your example doesn't use 'my'.

My use of Lua is part of Andy's GADS https://github.com/ctrlo/GADS, which is like a spreadsheet.  People can define their own columns, with configurable types... sometimes floats or integers.  People can also create columns which contain formulas, written in Lua.  The logic extracts the function parameter names from the Lua code, which must be names of columns.  But it's a little more complicated: some parameters to the Lua script are produced by an other Lua script, which may sometimes return an int or float or string or date.  Or sometimes they refer to spreadsheet cells which are references to other cells on other sheets.  There are also other cell types: in total 17 types.

So: data management is the core of this code and is complex.  In total 182 objects (pm files).  The flow from column value (float) to the Lua script call is quite complex in its flexability.  At least complex enough that I need to use 'my' copies between the place where the float value can be normalized to be a float (+0.0), into the function where parameters of mixed types are passed into Inline::Lua.  Each of these 'my' copies *may sometimes* break the NV-only status of the SV.   It will always be broken when I enabled debugging or logging on those values.

Of course I have been looking at work-arounds, because my code needs to be installed by other people as well.  It is not doable.  Now I still cannot run the official Inline::Lua.

**Comment by hoelzro** [comment]
Ah, ok - thanks for the details!  I definitely agree this is a bug - right now I'm just debating whether I should break things entirely with a 1.00 release, or if I should have a compilation flag that a user can provide `Makefile.PL`.

**Comment by hoelzro** [comment]
@markov2 Would you mind grabbing the code from the `prefer-nv` branch, testing it out, and verifying the fix?

**Comment by markov2** [comment]
I would like to add some regression tests to confirm the improvement, but apparently I cannot build the module directly from git.  What is the procedure to get a VERSION in?   I gave you a few examples already which you could use to add them to the regression tests: first to the current versions, when the test breaks.  Then cherry-pick them to the new branch.

I found one issue, which running perl 5.16: teh SVt_INVLIST was added around 5.19  (add #ifdef SVt_INVLIST).  One comment suggest it was previously named SVt_BIND which is missing from your list.

I think the ROK should move to the first spot.  You can use a refence as string and integer (in comparison)  But maybe also as a float (add 0.0).  It being a ref is certainly more important.

**Comment by hoelzro** [comment]
@markov2 I made the changes and pushed them up to the branch - I also attached a tarball for you to install:

[Inline-Lua-0.18-TRIAL.tar.gz](https://github.com/hoelzro/inline-lua/files/6527411/Inline-Lua-0.18-TRIAL.tar.gz)

**Comment by hoelzro** [comment]
(Don't mind the version number - I'd probably go with 1.00 for the actual release number due to the potential for breakage)

**Comment by hoelzro** [comment]
@markov2 Did you have a chance to try that trial release out?

**Comment by markov2** [comment]
No, I am starting-up a huge new project (actual 6 at the same time), so had to stall the module which uses yours for a moment.

But I have given you regression tests which demonstrate the problem.  When all tests pass, the code is correct ;-)

**Comment by hoelzro** [comment]
@markov2 Ok, just let me know when you have a chance to test it out!  I did add some tests based on your examples - if you have a chance to make sure I covered everything, that would be great!

**Comment by markov2** [comment]
All the artifacts seems to have disappeared.  I hope you did not get negative reports about the change.
